name: Checking Tests

on:
  pull_request:
    branches:
      - develop
      - staging

jobs:
  test:
    name: Checking Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Run Seed
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: npm run seed

      - name: Run Tests
        run: npm run test